### PR TITLE
Fix scheduleOnMembers method name

### PR DESCRIPTION
**Pull request by kwart**

### CODE REVIEW

**Comment by Serdaro** [comment]
@kwart , I have found some codes which include this method (`scheduleOnAllMembers`), e.g., https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/hazelcast/src/main/java/com/hazelcast/client/impl/proxy/ClientScheduledExecutorProxy.java or https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java

I am assuming we are aware of these.

**Comment by kwart** [comment]
There are both `scheduleOnAllMembers` and `scheduleOnMembers`. The second one takes a collection of members as an argument.

**Comment by kwart** [comment]
This is the interface implemented:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/IScheduledExecutorService.java

**Review by Serdaro — APPROVED** [review]

**Comment by Serdaro** [comment]
Will take care of the dead link.

**Comment by JakeSCahill** [comment]
> Will take care of the dead link.

Thanks @Serdaro 😄  Looks like an old link to the Jet reference manual.

@naadhira this will fix the dead link for your PR too.

**Pull request merged**
